---
title: "Community Contributor Winners"
author: "Bill Carney"
date: "9/22/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## The RStudio Community

We're excited to announce the latest prize winners from the [RStudio Community](https://community.rstudio.com/).We've randomly selected five individuals, weighted by the number of likes they received. We will be reaching out to each winner directly to be able to ship them their awards.

The first award is an RStudio t-shirt and all of the hex and RStudio stickers we can find.  The winners for the week of September 22nd are:

Name| likes
------|-----
mara| 61 
alistaire| 45 
daattali| 29 
emilyriederer| 17 
eric_bickel| 12 

We’re excited to announce the prize winners for the second week. The award is an RStudio t-shirt and all of the hex and RStudio stickers we can find. Don’t worry, we are building up to better stuff. As with last week we will be reaching out to each winner directly to be able to ship them their awards. The winners for the week of September 29th are:

Name| likes
------|-----
nick| 48 
jessemaegan| 42 
raybuhr| 14 
billR| 7 
mmuurr| 6 

We’re excited to announce the prize winners for the third week. The award is an RStudio t-shirt and all of the hex and RStudio stickers we can find. The winners for the week of October 6th are:

Name| likes
------|-----
apreshill| 19 
pavopax| 11 
mfherman| 10 
rensa| 7 
tomtec| 4 

We’re excited to announce the prize winners for the fourth week. The award is an RStudio t-shirt and all of the hex and RStudio stickers we can find. The winners for the week of October 13th are:

Name| likes
------|-----
pssguy| 15 
cdr6934| 5 
rpodcast| 5 
Andrea| 4 
timpe| 2 

Week #5 winners. The award is an RStudio t-shirt and all of the hex and RStudio stickers we can find. The winners for the week of October 20th are:

Name| likes
------|-----
cderv| 10 
PirateGrunt| 4 
mungojam| 3 
rkahne| 3 
DaveRGP| 2 

Week #6 winners will receive an RStudio t-shirt and all of the hex and RStudio stickers we can find. The winners for the week of October 27th are:

Name| likes
------|-----
danr| 17 
jim89| 8 
nakamichi| 4 
Ranae| 4 
jasonserviss| 1 


Sorry for the delay! Week #7 winners will receive an RStudio t-shirt and all of the hex and RStudio stickers we can find. The winners for the week of November 3rd are:

Name| likes
------|-----
FlorianGD| 5 
Damian| 4 
jtr13| 3 
RStudioUser| 1 
robertmitchellv| 1 


We missed a week! Week #8 and #9 winners will receive an RStudio t-shirt and all of the hex and RStudio stickers we can find. The winners for the week of November 10th & 17th are:

Name| likes
------|-----
jakekaupp| 12 
taraas| 10 
hinkelman| 5 
tyluRp| 5 
Tazinho| 3 
Anantadinath| 2 
scw| 2 
raviolli77| 1 
yonicd| 1 
yutannihilation| 1 
